// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mqtt "github.com/absmach/propeller/pkg/mqtt"
	mock "github.com/stretchr/testify/mock"
)

// MockPubSub is an autogenerated mock type for the PubSub type
type MockPubSub struct {
	mock.Mock
}

type MockPubSub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPubSub) EXPECT() *MockPubSub_Expecter {
	return &MockPubSub_Expecter{mock: &_m.Mock}
}

// Disconnect provides a mock function with given fields: ctx
func (_m *MockPubSub) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPubSub_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockPubSub_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPubSub_Expecter) Disconnect(ctx interface{}) *MockPubSub_Disconnect_Call {
	return &MockPubSub_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *MockPubSub_Disconnect_Call) Run(run func(ctx context.Context)) *MockPubSub_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPubSub_Disconnect_Call) Return(_a0 error) *MockPubSub_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPubSub_Disconnect_Call) RunAndReturn(run func(context.Context) error) *MockPubSub_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, topic, msg
func (_m *MockPubSub) Publish(ctx context.Context, topic string, msg interface{}) error {
	ret := _m.Called(ctx, topic, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, topic, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPubSub_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPubSub_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - msg interface{}
func (_e *MockPubSub_Expecter) Publish(ctx interface{}, topic interface{}, msg interface{}) *MockPubSub_Publish_Call {
	return &MockPubSub_Publish_Call{Call: _e.mock.On("Publish", ctx, topic, msg)}
}

func (_c *MockPubSub_Publish_Call) Run(run func(ctx context.Context, topic string, msg interface{})) *MockPubSub_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockPubSub_Publish_Call) Return(_a0 error) *MockPubSub_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPubSub_Publish_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockPubSub_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, topic, handler
func (_m *MockPubSub) Subscribe(ctx context.Context, topic string, handler mqtt.Handler) error {
	ret := _m.Called(ctx, topic, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, mqtt.Handler) error); ok {
		r0 = rf(ctx, topic, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPubSub_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockPubSub_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - handler mqtt.Handler
func (_e *MockPubSub_Expecter) Subscribe(ctx interface{}, topic interface{}, handler interface{}) *MockPubSub_Subscribe_Call {
	return &MockPubSub_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topic, handler)}
}

func (_c *MockPubSub_Subscribe_Call) Run(run func(ctx context.Context, topic string, handler mqtt.Handler)) *MockPubSub_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(mqtt.Handler))
	})
	return _c
}

func (_c *MockPubSub_Subscribe_Call) Return(_a0 error) *MockPubSub_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPubSub_Subscribe_Call) RunAndReturn(run func(context.Context, string, mqtt.Handler) error) *MockPubSub_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: ctx, topic
func (_m *MockPubSub) Unsubscribe(ctx context.Context, topic string) error {
	ret := _m.Called(ctx, topic)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPubSub_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockPubSub_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
func (_e *MockPubSub_Expecter) Unsubscribe(ctx interface{}, topic interface{}) *MockPubSub_Unsubscribe_Call {
	return &MockPubSub_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx, topic)}
}

func (_c *MockPubSub_Unsubscribe_Call) Run(run func(ctx context.Context, topic string)) *MockPubSub_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPubSub_Unsubscribe_Call) Return(_a0 error) *MockPubSub_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPubSub_Unsubscribe_Call) RunAndReturn(run func(context.Context, string) error) *MockPubSub_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPubSub creates a new instance of MockPubSub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPubSub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPubSub {
	mock := &MockPubSub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
