// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/propeller/pkg/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsRepository creates a new instance of MockMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRepository {
	mock := &MockMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsRepository is an autogenerated mock type for the MetricsRepository type
type MockMetricsRepository struct {
	mock.Mock
}

type MockMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRepository) EXPECT() *MockMetricsRepository_Expecter {
	return &MockMetricsRepository_Expecter{mock: &_m.Mock}
}

// CreatePropletMetrics provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) CreatePropletMetrics(ctx context.Context, m storage.PropletMetrics) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreatePropletMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.PropletMetrics) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_CreatePropletMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePropletMetrics'
type MockMetricsRepository_CreatePropletMetrics_Call struct {
	*mock.Call
}

// CreatePropletMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - m storage.PropletMetrics
func (_e *MockMetricsRepository_Expecter) CreatePropletMetrics(ctx interface{}, m interface{}) *MockMetricsRepository_CreatePropletMetrics_Call {
	return &MockMetricsRepository_CreatePropletMetrics_Call{Call: _e.mock.On("CreatePropletMetrics", ctx, m)}
}

func (_c *MockMetricsRepository_CreatePropletMetrics_Call) Run(run func(ctx context.Context, m storage.PropletMetrics)) *MockMetricsRepository_CreatePropletMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.PropletMetrics
		if args[1] != nil {
			arg1 = args[1].(storage.PropletMetrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_CreatePropletMetrics_Call) Return(err error) *MockMetricsRepository_CreatePropletMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_CreatePropletMetrics_Call) RunAndReturn(run func(ctx context.Context, m storage.PropletMetrics) error) *MockMetricsRepository_CreatePropletMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTaskMetrics provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) CreateTaskMetrics(ctx context.Context, m storage.TaskMetrics) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaskMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.TaskMetrics) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_CreateTaskMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaskMetrics'
type MockMetricsRepository_CreateTaskMetrics_Call struct {
	*mock.Call
}

// CreateTaskMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - m storage.TaskMetrics
func (_e *MockMetricsRepository_Expecter) CreateTaskMetrics(ctx interface{}, m interface{}) *MockMetricsRepository_CreateTaskMetrics_Call {
	return &MockMetricsRepository_CreateTaskMetrics_Call{Call: _e.mock.On("CreateTaskMetrics", ctx, m)}
}

func (_c *MockMetricsRepository_CreateTaskMetrics_Call) Run(run func(ctx context.Context, m storage.TaskMetrics)) *MockMetricsRepository_CreateTaskMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.TaskMetrics
		if args[1] != nil {
			arg1 = args[1].(storage.TaskMetrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_CreateTaskMetrics_Call) Return(err error) *MockMetricsRepository_CreateTaskMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_CreateTaskMetrics_Call) RunAndReturn(run func(ctx context.Context, m storage.TaskMetrics) error) *MockMetricsRepository_CreateTaskMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// ListPropletMetrics provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) ListPropletMetrics(ctx context.Context, propletID string, offset uint64, limit uint64) ([]storage.PropletMetrics, uint64, error) {
	ret := _mock.Called(ctx, propletID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPropletMetrics")
	}

	var r0 []storage.PropletMetrics
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]storage.PropletMetrics, uint64, error)); ok {
		return returnFunc(ctx, propletID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []storage.PropletMetrics); ok {
		r0 = returnFunc(ctx, propletID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.PropletMetrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) uint64); ok {
		r1 = returnFunc(ctx, propletID, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, uint64, uint64) error); ok {
		r2 = returnFunc(ctx, propletID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMetricsRepository_ListPropletMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPropletMetrics'
type MockMetricsRepository_ListPropletMetrics_Call struct {
	*mock.Call
}

// ListPropletMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - propletID string
//   - offset uint64
//   - limit uint64
func (_e *MockMetricsRepository_Expecter) ListPropletMetrics(ctx interface{}, propletID interface{}, offset interface{}, limit interface{}) *MockMetricsRepository_ListPropletMetrics_Call {
	return &MockMetricsRepository_ListPropletMetrics_Call{Call: _e.mock.On("ListPropletMetrics", ctx, propletID, offset, limit)}
}

func (_c *MockMetricsRepository_ListPropletMetrics_Call) Run(run func(ctx context.Context, propletID string, offset uint64, limit uint64)) *MockMetricsRepository_ListPropletMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_ListPropletMetrics_Call) Return(propletMetricss []storage.PropletMetrics, v uint64, err error) *MockMetricsRepository_ListPropletMetrics_Call {
	_c.Call.Return(propletMetricss, v, err)
	return _c
}

func (_c *MockMetricsRepository_ListPropletMetrics_Call) RunAndReturn(run func(ctx context.Context, propletID string, offset uint64, limit uint64) ([]storage.PropletMetrics, uint64, error)) *MockMetricsRepository_ListPropletMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskMetrics provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) ListTaskMetrics(ctx context.Context, taskID string, offset uint64, limit uint64) ([]storage.TaskMetrics, uint64, error) {
	ret := _mock.Called(ctx, taskID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskMetrics")
	}

	var r0 []storage.TaskMetrics
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]storage.TaskMetrics, uint64, error)); ok {
		return returnFunc(ctx, taskID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []storage.TaskMetrics); ok {
		r0 = returnFunc(ctx, taskID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.TaskMetrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) uint64); ok {
		r1 = returnFunc(ctx, taskID, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, uint64, uint64) error); ok {
		r2 = returnFunc(ctx, taskID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMetricsRepository_ListTaskMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskMetrics'
type MockMetricsRepository_ListTaskMetrics_Call struct {
	*mock.Call
}

// ListTaskMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - offset uint64
//   - limit uint64
func (_e *MockMetricsRepository_Expecter) ListTaskMetrics(ctx interface{}, taskID interface{}, offset interface{}, limit interface{}) *MockMetricsRepository_ListTaskMetrics_Call {
	return &MockMetricsRepository_ListTaskMetrics_Call{Call: _e.mock.On("ListTaskMetrics", ctx, taskID, offset, limit)}
}

func (_c *MockMetricsRepository_ListTaskMetrics_Call) Run(run func(ctx context.Context, taskID string, offset uint64, limit uint64)) *MockMetricsRepository_ListTaskMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_ListTaskMetrics_Call) Return(taskMetricss []storage.TaskMetrics, v uint64, err error) *MockMetricsRepository_ListTaskMetrics_Call {
	_c.Call.Return(taskMetricss, v, err)
	return _c
}

func (_c *MockMetricsRepository_ListTaskMetrics_Call) RunAndReturn(run func(ctx context.Context, taskID string, offset uint64, limit uint64) ([]storage.TaskMetrics, uint64, error)) *MockMetricsRepository_ListTaskMetrics_Call {
	_c.Call.Return(run)
	return _c
}
