// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	storage "github.com/absmach/propeller/pkg/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockMetricsRepository is an autogenerated mock type for the MetricsRepository type
type MockMetricsRepository struct {
	mock.Mock
}

type MockMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRepository) EXPECT() *MockMetricsRepository_Expecter {
	return &MockMetricsRepository_Expecter{mock: &_m.Mock}
}

// CreatePropletMetrics provides a mock function with given fields: ctx, m
func (_m *MockMetricsRepository) CreatePropletMetrics(ctx context.Context, m storage.PropletMetrics) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreatePropletMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.PropletMetrics) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsRepository_CreatePropletMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePropletMetrics'
type MockMetricsRepository_CreatePropletMetrics_Call struct {
	*mock.Call
}

// CreatePropletMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - m storage.PropletMetrics
func (_e *MockMetricsRepository_Expecter) CreatePropletMetrics(ctx interface{}, m interface{}) *MockMetricsRepository_CreatePropletMetrics_Call {
	return &MockMetricsRepository_CreatePropletMetrics_Call{Call: _e.mock.On("CreatePropletMetrics", ctx, m)}
}

func (_c *MockMetricsRepository_CreatePropletMetrics_Call) Run(run func(ctx context.Context, m storage.PropletMetrics)) *MockMetricsRepository_CreatePropletMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(storage.PropletMetrics))
	})
	return _c
}

func (_c *MockMetricsRepository_CreatePropletMetrics_Call) Return(_a0 error) *MockMetricsRepository_CreatePropletMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsRepository_CreatePropletMetrics_Call) RunAndReturn(run func(context.Context, storage.PropletMetrics) error) *MockMetricsRepository_CreatePropletMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTaskMetrics provides a mock function with given fields: ctx, m
func (_m *MockMetricsRepository) CreateTaskMetrics(ctx context.Context, m storage.TaskMetrics) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaskMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.TaskMetrics) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsRepository_CreateTaskMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaskMetrics'
type MockMetricsRepository_CreateTaskMetrics_Call struct {
	*mock.Call
}

// CreateTaskMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - m storage.TaskMetrics
func (_e *MockMetricsRepository_Expecter) CreateTaskMetrics(ctx interface{}, m interface{}) *MockMetricsRepository_CreateTaskMetrics_Call {
	return &MockMetricsRepository_CreateTaskMetrics_Call{Call: _e.mock.On("CreateTaskMetrics", ctx, m)}
}

func (_c *MockMetricsRepository_CreateTaskMetrics_Call) Run(run func(ctx context.Context, m storage.TaskMetrics)) *MockMetricsRepository_CreateTaskMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(storage.TaskMetrics))
	})
	return _c
}

func (_c *MockMetricsRepository_CreateTaskMetrics_Call) Return(_a0 error) *MockMetricsRepository_CreateTaskMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsRepository_CreateTaskMetrics_Call) RunAndReturn(run func(context.Context, storage.TaskMetrics) error) *MockMetricsRepository_CreateTaskMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// ListPropletMetrics provides a mock function with given fields: ctx, propletID, offset, limit
func (_m *MockMetricsRepository) ListPropletMetrics(ctx context.Context, propletID string, offset uint64, limit uint64) ([]storage.PropletMetrics, uint64, error) {
	ret := _m.Called(ctx, propletID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPropletMetrics")
	}

	var r0 []storage.PropletMetrics
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]storage.PropletMetrics, uint64, error)); ok {
		return rf(ctx, propletID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []storage.PropletMetrics); ok {
		r0 = rf(ctx, propletID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.PropletMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) uint64); ok {
		r1 = rf(ctx, propletID, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, uint64, uint64) error); ok {
		r2 = rf(ctx, propletID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMetricsRepository_ListPropletMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPropletMetrics'
type MockMetricsRepository_ListPropletMetrics_Call struct {
	*mock.Call
}

// ListPropletMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - propletID string
//   - offset uint64
//   - limit uint64
func (_e *MockMetricsRepository_Expecter) ListPropletMetrics(ctx interface{}, propletID interface{}, offset interface{}, limit interface{}) *MockMetricsRepository_ListPropletMetrics_Call {
	return &MockMetricsRepository_ListPropletMetrics_Call{Call: _e.mock.On("ListPropletMetrics", ctx, propletID, offset, limit)}
}

func (_c *MockMetricsRepository_ListPropletMetrics_Call) Run(run func(ctx context.Context, propletID string, offset uint64, limit uint64)) *MockMetricsRepository_ListPropletMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint64), args[3].(uint64))
	})
	return _c
}

func (_c *MockMetricsRepository_ListPropletMetrics_Call) Return(_a0 []storage.PropletMetrics, _a1 uint64, _a2 error) *MockMetricsRepository_ListPropletMetrics_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMetricsRepository_ListPropletMetrics_Call) RunAndReturn(run func(context.Context, string, uint64, uint64) ([]storage.PropletMetrics, uint64, error)) *MockMetricsRepository_ListPropletMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskMetrics provides a mock function with given fields: ctx, taskID, offset, limit
func (_m *MockMetricsRepository) ListTaskMetrics(ctx context.Context, taskID string, offset uint64, limit uint64) ([]storage.TaskMetrics, uint64, error) {
	ret := _m.Called(ctx, taskID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskMetrics")
	}

	var r0 []storage.TaskMetrics
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]storage.TaskMetrics, uint64, error)); ok {
		return rf(ctx, taskID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []storage.TaskMetrics); ok {
		r0 = rf(ctx, taskID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.TaskMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) uint64); ok {
		r1 = rf(ctx, taskID, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, uint64, uint64) error); ok {
		r2 = rf(ctx, taskID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMetricsRepository_ListTaskMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskMetrics'
type MockMetricsRepository_ListTaskMetrics_Call struct {
	*mock.Call
}

// ListTaskMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - offset uint64
//   - limit uint64
func (_e *MockMetricsRepository_Expecter) ListTaskMetrics(ctx interface{}, taskID interface{}, offset interface{}, limit interface{}) *MockMetricsRepository_ListTaskMetrics_Call {
	return &MockMetricsRepository_ListTaskMetrics_Call{Call: _e.mock.On("ListTaskMetrics", ctx, taskID, offset, limit)}
}

func (_c *MockMetricsRepository_ListTaskMetrics_Call) Run(run func(ctx context.Context, taskID string, offset uint64, limit uint64)) *MockMetricsRepository_ListTaskMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint64), args[3].(uint64))
	})
	return _c
}

func (_c *MockMetricsRepository_ListTaskMetrics_Call) Return(_a0 []storage.TaskMetrics, _a1 uint64, _a2 error) *MockMetricsRepository_ListTaskMetrics_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMetricsRepository_ListTaskMetrics_Call) RunAndReturn(run func(context.Context, string, uint64, uint64) ([]storage.TaskMetrics, uint64, error)) *MockMetricsRepository_ListTaskMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsRepository creates a new instance of MockMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRepository {
	mock := &MockMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
