// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/absmach/propeller/pkg/proplet"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPropletRepository creates a new instance of MockPropletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPropletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPropletRepository {
	mock := &MockPropletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPropletRepository is an autogenerated mock type for the PropletRepository type
type MockPropletRepository struct {
	mock.Mock
}

type MockPropletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPropletRepository) EXPECT() *MockPropletRepository_Expecter {
	return &MockPropletRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPropletRepository
func (_mock *MockPropletRepository) Create(ctx context.Context, p proplet.Proplet) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, proplet.Proplet) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPropletRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPropletRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p proplet.Proplet
func (_e *MockPropletRepository_Expecter) Create(ctx interface{}, p interface{}) *MockPropletRepository_Create_Call {
	return &MockPropletRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockPropletRepository_Create_Call) Run(run func(ctx context.Context, p proplet.Proplet)) *MockPropletRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 proplet.Proplet
		if args[1] != nil {
			arg1 = args[1].(proplet.Proplet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPropletRepository_Create_Call) Return(err error) *MockPropletRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPropletRepository_Create_Call) RunAndReturn(run func(ctx context.Context, p proplet.Proplet) error) *MockPropletRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPropletRepository
func (_mock *MockPropletRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPropletRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPropletRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPropletRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPropletRepository_Delete_Call {
	return &MockPropletRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPropletRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockPropletRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPropletRepository_Delete_Call) Return(err error) *MockPropletRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPropletRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockPropletRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPropletRepository
func (_mock *MockPropletRepository) Get(ctx context.Context, id string) (proplet.Proplet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 proplet.Proplet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (proplet.Proplet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) proplet.Proplet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(proplet.Proplet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPropletRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPropletRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPropletRepository_Expecter) Get(ctx interface{}, id interface{}) *MockPropletRepository_Get_Call {
	return &MockPropletRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockPropletRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockPropletRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPropletRepository_Get_Call) Return(proplet1 proplet.Proplet, err error) *MockPropletRepository_Get_Call {
	_c.Call.Return(proplet1, err)
	return _c
}

func (_c *MockPropletRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (proplet.Proplet, error)) *MockPropletRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPropletRepository
func (_mock *MockPropletRepository) List(ctx context.Context, offset uint64, limit uint64) ([]proplet.Proplet, uint64, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []proplet.Proplet
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]proplet.Proplet, uint64, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) []proplet.Proplet); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]proplet.Proplet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) uint64); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint64, uint64) error); ok {
		r2 = returnFunc(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPropletRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPropletRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *MockPropletRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockPropletRepository_List_Call {
	return &MockPropletRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockPropletRepository_List_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *MockPropletRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPropletRepository_List_Call) Return(proplets []proplet.Proplet, v uint64, err error) *MockPropletRepository_List_Call {
	_c.Call.Return(proplets, v, err)
	return _c
}

func (_c *MockPropletRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset uint64, limit uint64) ([]proplet.Proplet, uint64, error)) *MockPropletRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockPropletRepository) ListByAlive(ctx context.Context, offset uint64, limit uint64, alive bool, since time.Time) ([]proplet.Proplet, uint64, error) {
	ret := _mock.Called(ctx, offset, limit, alive, since)

	if len(ret) == 0 {
		panic("no return value specified for ListByAlive")
	}

	var r0 []proplet.Proplet
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool, time.Time) ([]proplet.Proplet, uint64, error)); ok {
		return returnFunc(ctx, offset, limit, alive, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool, time.Time) []proplet.Proplet); ok {
		r0 = returnFunc(ctx, offset, limit, alive, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]proplet.Proplet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, bool, time.Time) uint64); ok {
		r1 = returnFunc(ctx, offset, limit, alive, since)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint64, uint64, bool, time.Time) error); ok {
		r2 = returnFunc(ctx, offset, limit, alive, since)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

type MockPropletRepository_ListByAlive_Call struct {
	*mock.Call
}

func (_e *MockPropletRepository_Expecter) ListByAlive(ctx interface{}, offset interface{}, limit interface{}, alive interface{}, since interface{}) *MockPropletRepository_ListByAlive_Call {
	return &MockPropletRepository_ListByAlive_Call{Call: _e.mock.On("ListByAlive", ctx, offset, limit, alive, since)}
}

func (_c *MockPropletRepository_ListByAlive_Call) Run(run func(ctx context.Context, offset uint64, limit uint64, alive bool, since time.Time)) *MockPropletRepository_ListByAlive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(arg0, arg1, arg2, arg3, arg4)
	})
	return _c
}

func (_c *MockPropletRepository_ListByAlive_Call) Return(proplets []proplet.Proplet, v uint64, err error) *MockPropletRepository_ListByAlive_Call {
	_c.Call.Return(proplets, v, err)
	return _c
}

func (_c *MockPropletRepository_ListByAlive_Call) RunAndReturn(run func(ctx context.Context, offset uint64, limit uint64, alive bool, since time.Time) ([]proplet.Proplet, uint64, error)) *MockPropletRepository_ListByAlive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPropletRepository
func (_mock *MockPropletRepository) Update(ctx context.Context, p proplet.Proplet) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, proplet.Proplet) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPropletRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPropletRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p proplet.Proplet
func (_e *MockPropletRepository_Expecter) Update(ctx interface{}, p interface{}) *MockPropletRepository_Update_Call {
	return &MockPropletRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockPropletRepository_Update_Call) Run(run func(ctx context.Context, p proplet.Proplet)) *MockPropletRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 proplet.Proplet
		if args[1] != nil {
			arg1 = args[1].(proplet.Proplet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPropletRepository_Update_Call) Return(err error) *MockPropletRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPropletRepository_Update_Call) RunAndReturn(run func(ctx context.Context, p proplet.Proplet) error) *MockPropletRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockPropletRepository) GetAliveHistory(ctx context.Context, id string, offset uint64, limit uint64) ([]time.Time, uint64, error) {
	ret := _mock.Called(ctx, id, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAliveHistory")
	}

	var r0 []time.Time
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]time.Time, uint64, error)); ok {
		return returnFunc(ctx, id, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []time.Time); ok {
		r0 = returnFunc(ctx, id, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) uint64); ok {
		r1 = returnFunc(ctx, id, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, uint64, uint64) error); ok {
		r2 = returnFunc(ctx, id, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

type MockPropletRepository_GetAliveHistory_Call struct {
	*mock.Call
}

func (_e *MockPropletRepository_Expecter) GetAliveHistory(ctx interface{}, id interface{}, offset interface{}, limit interface{}) *MockPropletRepository_GetAliveHistory_Call {
	return &MockPropletRepository_GetAliveHistory_Call{Call: _e.mock.On("GetAliveHistory", ctx, id, offset, limit)}
}

func (_c *MockPropletRepository_GetAliveHistory_Call) Run(run func(ctx context.Context, id string, offset uint64, limit uint64)) *MockPropletRepository_GetAliveHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockPropletRepository_GetAliveHistory_Call) Return(history []time.Time, total uint64, err error) *MockPropletRepository_GetAliveHistory_Call {
	_c.Call.Return(history, total, err)
	return _c
}

func (_c *MockPropletRepository_GetAliveHistory_Call) RunAndReturn(run func(ctx context.Context, id string, offset uint64, limit uint64) ([]time.Time, uint64, error)) *MockPropletRepository_GetAliveHistory_Call {
	_c.Call.Return(run)
	return _c
}
