// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	proplet "github.com/absmach/propeller/pkg/proplet"
	mock "github.com/stretchr/testify/mock"
)

// MockPropletRepository is an autogenerated mock type for the PropletRepository type
type MockPropletRepository struct {
	mock.Mock
}

type MockPropletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPropletRepository) EXPECT() *MockPropletRepository_Expecter {
	return &MockPropletRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockPropletRepository) Create(ctx context.Context, p proplet.Proplet) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, proplet.Proplet) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPropletRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPropletRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p proplet.Proplet
func (_e *MockPropletRepository_Expecter) Create(ctx interface{}, p interface{}) *MockPropletRepository_Create_Call {
	return &MockPropletRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockPropletRepository_Create_Call) Run(run func(ctx context.Context, p proplet.Proplet)) *MockPropletRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(proplet.Proplet))
	})
	return _c
}

func (_c *MockPropletRepository_Create_Call) Return(_a0 error) *MockPropletRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPropletRepository_Create_Call) RunAndReturn(run func(context.Context, proplet.Proplet) error) *MockPropletRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPropletRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPropletRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPropletRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPropletRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPropletRepository_Delete_Call {
	return &MockPropletRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPropletRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockPropletRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPropletRepository_Delete_Call) Return(_a0 error) *MockPropletRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPropletRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockPropletRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockPropletRepository) Get(ctx context.Context, id string) (proplet.Proplet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 proplet.Proplet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (proplet.Proplet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) proplet.Proplet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(proplet.Proplet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPropletRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPropletRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPropletRepository_Expecter) Get(ctx interface{}, id interface{}) *MockPropletRepository_Get_Call {
	return &MockPropletRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockPropletRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockPropletRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPropletRepository_Get_Call) Return(_a0 proplet.Proplet, _a1 error) *MockPropletRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPropletRepository_Get_Call) RunAndReturn(run func(context.Context, string) (proplet.Proplet, error)) *MockPropletRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MockPropletRepository) List(ctx context.Context, offset uint64, limit uint64) ([]proplet.Proplet, uint64, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []proplet.Proplet
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]proplet.Proplet, uint64, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []proplet.Proplet); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]proplet.Proplet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) uint64); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, uint64) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPropletRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPropletRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *MockPropletRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockPropletRepository_List_Call {
	return &MockPropletRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockPropletRepository_List_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *MockPropletRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockPropletRepository_List_Call) Return(_a0 []proplet.Proplet, _a1 uint64, _a2 error) *MockPropletRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPropletRepository_List_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]proplet.Proplet, uint64, error)) *MockPropletRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockPropletRepository) Update(ctx context.Context, p proplet.Proplet) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, proplet.Proplet) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPropletRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPropletRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p proplet.Proplet
func (_e *MockPropletRepository_Expecter) Update(ctx interface{}, p interface{}) *MockPropletRepository_Update_Call {
	return &MockPropletRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockPropletRepository_Update_Call) Run(run func(ctx context.Context, p proplet.Proplet)) *MockPropletRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(proplet.Proplet))
	})
	return _c
}

func (_c *MockPropletRepository_Update_Call) Return(_a0 error) *MockPropletRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPropletRepository_Update_Call) RunAndReturn(run func(context.Context, proplet.Proplet) error) *MockPropletRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPropletRepository creates a new instance of MockPropletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPropletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPropletRepository {
	mock := &MockPropletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
