// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskPropletRepository creates a new instance of MockTaskPropletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskPropletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskPropletRepository {
	mock := &MockTaskPropletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskPropletRepository is an autogenerated mock type for the TaskPropletRepository type
type MockTaskPropletRepository struct {
	mock.Mock
}

type MockTaskPropletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskPropletRepository) EXPECT() *MockTaskPropletRepository_Expecter {
	return &MockTaskPropletRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskPropletRepository
func (_mock *MockTaskPropletRepository) Create(ctx context.Context, taskID string, propletID string) error {
	ret := _mock.Called(ctx, taskID, propletID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, taskID, propletID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskPropletRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskPropletRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - propletID string
func (_e *MockTaskPropletRepository_Expecter) Create(ctx interface{}, taskID interface{}, propletID interface{}) *MockTaskPropletRepository_Create_Call {
	return &MockTaskPropletRepository_Create_Call{Call: _e.mock.On("Create", ctx, taskID, propletID)}
}

func (_c *MockTaskPropletRepository_Create_Call) Run(run func(ctx context.Context, taskID string, propletID string)) *MockTaskPropletRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskPropletRepository_Create_Call) Return(err error) *MockTaskPropletRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskPropletRepository_Create_Call) RunAndReturn(run func(ctx context.Context, taskID string, propletID string) error) *MockTaskPropletRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskPropletRepository
func (_mock *MockTaskPropletRepository) Delete(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskPropletRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskPropletRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockTaskPropletRepository_Expecter) Delete(ctx interface{}, taskID interface{}) *MockTaskPropletRepository_Delete_Call {
	return &MockTaskPropletRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, taskID)}
}

func (_c *MockTaskPropletRepository_Delete_Call) Run(run func(ctx context.Context, taskID string)) *MockTaskPropletRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskPropletRepository_Delete_Call) Return(err error) *MockTaskPropletRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskPropletRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *MockTaskPropletRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTaskPropletRepository
func (_mock *MockTaskPropletRepository) Get(ctx context.Context, taskID string) (string, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskPropletRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskPropletRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockTaskPropletRepository_Expecter) Get(ctx interface{}, taskID interface{}) *MockTaskPropletRepository_Get_Call {
	return &MockTaskPropletRepository_Get_Call{Call: _e.mock.On("Get", ctx, taskID)}
}

func (_c *MockTaskPropletRepository_Get_Call) Run(run func(ctx context.Context, taskID string)) *MockTaskPropletRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskPropletRepository_Get_Call) Return(s string, err error) *MockTaskPropletRepository_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTaskPropletRepository_Get_Call) RunAndReturn(run func(ctx context.Context, taskID string) (string, error)) *MockTaskPropletRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}
