// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/propeller/pkg/task"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Create(ctx context.Context, t task.Task) (task.Task, error) {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) (task.Task, error)); ok {
		return returnFunc(ctx, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) task.Task); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Get(0).(task.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task.Task) error); ok {
		r1 = returnFunc(ctx, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t task.Task
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, t interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, t task.Task)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.Task
		if args[1] != nil {
			arg1 = args[1].(task.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(task1 task.Task, err error) *MockTaskRepository_Create_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(ctx context.Context, t task.Task) (task.Task, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(err error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Get(ctx context.Context, id string) (task.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (task.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) task.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(task.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskRepository_Expecter) Get(ctx interface{}, id interface{}) *MockTaskRepository_Get_Call {
	return &MockTaskRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTaskRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockTaskRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Get_Call) Return(task1 task.Task, err error) *MockTaskRepository_Get_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTaskRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (task.Task, error)) *MockTaskRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) List(ctx context.Context, offset uint64, limit uint64) ([]task.Task, uint64, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []task.Task
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]task.Task, uint64, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) []task.Task); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) uint64); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint64, uint64) error); ok {
		r2 = returnFunc(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTaskRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *MockTaskRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockTaskRepository_List_Call {
	return &MockTaskRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockTaskRepository_List_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *MockTaskRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_List_Call) Return(tasks []task.Task, v uint64, err error) *MockTaskRepository_List_Call {
	_c.Call.Return(tasks, v, err)
	return _c
}

func (_c *MockTaskRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset uint64, limit uint64) ([]task.Task, uint64, error)) *MockTaskRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByJobID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) ListByJobID(ctx context.Context, jobID string) ([]task.Task, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for ListByJobID")
	}

	var r0 []task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]task.Task, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []task.Task); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_ListByJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByJobID'
type MockTaskRepository_ListByJobID_Call struct {
	*mock.Call
}

// ListByJobID is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockTaskRepository_Expecter) ListByJobID(ctx interface{}, jobID interface{}) *MockTaskRepository_ListByJobID_Call {
	return &MockTaskRepository_ListByJobID_Call{Call: _e.mock.On("ListByJobID", ctx, jobID)}
}

func (_c *MockTaskRepository_ListByJobID_Call) Run(run func(ctx context.Context, jobID string)) *MockTaskRepository_ListByJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_ListByJobID_Call) Return(tasks []task.Task, err error) *MockTaskRepository_ListByJobID_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_ListByJobID_Call) RunAndReturn(run func(ctx context.Context, jobID string) ([]task.Task, error)) *MockTaskRepository_ListByJobID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByWorkflowID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) ListByWorkflowID(ctx context.Context, workflowID string) ([]task.Task, error) {
	ret := _mock.Called(ctx, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for ListByWorkflowID")
	}

	var r0 []task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]task.Task, error)); ok {
		return returnFunc(ctx, workflowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []task.Task); ok {
		r0 = returnFunc(ctx, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workflowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_ListByWorkflowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByWorkflowID'
type MockTaskRepository_ListByWorkflowID_Call struct {
	*mock.Call
}

// ListByWorkflowID is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID string
func (_e *MockTaskRepository_Expecter) ListByWorkflowID(ctx interface{}, workflowID interface{}) *MockTaskRepository_ListByWorkflowID_Call {
	return &MockTaskRepository_ListByWorkflowID_Call{Call: _e.mock.On("ListByWorkflowID", ctx, workflowID)}
}

func (_c *MockTaskRepository_ListByWorkflowID_Call) Run(run func(ctx context.Context, workflowID string)) *MockTaskRepository_ListByWorkflowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_ListByWorkflowID_Call) Return(tasks []task.Task, err error) *MockTaskRepository_ListByWorkflowID_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_ListByWorkflowID_Call) RunAndReturn(run func(ctx context.Context, workflowID string) ([]task.Task, error)) *MockTaskRepository_ListByWorkflowID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Update(ctx context.Context, t task.Task) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t task.Task
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, t interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, t task.Task)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.Task
		if args[1] != nil {
			arg1 = args[1].(task.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(err error) *MockTaskRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(ctx context.Context, t task.Task) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
