// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	task "github.com/absmach/propeller/pkg/task"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *MockTaskRepository) Create(ctx context.Context, t task.Task) (task.Task, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, task.Task) (task.Task, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.Task) task.Task); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Get(0).(task.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.Task) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t task.Task
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, t interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, t task.Task)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.Task))
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(_a0 task.Task, _a1 error) *MockTaskRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(context.Context, task.Task) (task.Task, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTaskRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(_a0 error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockTaskRepository) Get(ctx context.Context, id string) (task.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (task.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) task.Task); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(task.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskRepository_Expecter) Get(ctx interface{}, id interface{}) *MockTaskRepository_Get_Call {
	return &MockTaskRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTaskRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockTaskRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskRepository_Get_Call) Return(_a0 task.Task, _a1 error) *MockTaskRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_Get_Call) RunAndReturn(run func(context.Context, string) (task.Task, error)) *MockTaskRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MockTaskRepository) List(ctx context.Context, offset uint64, limit uint64) ([]task.Task, uint64, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []task.Task
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]task.Task, uint64, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []task.Task); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) uint64); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, uint64) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTaskRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *MockTaskRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockTaskRepository_List_Call {
	return &MockTaskRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockTaskRepository_List_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *MockTaskRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockTaskRepository_List_Call) Return(_a0 []task.Task, _a1 uint64, _a2 error) *MockTaskRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTaskRepository_List_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]task.Task, uint64, error)) *MockTaskRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, t
func (_m *MockTaskRepository) Update(ctx context.Context, t task.Task) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, task.Task) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t task.Task
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, t interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, t task.Task)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.Task))
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(_a0 error) *MockTaskRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(context.Context, task.Task) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
