package elastic:hal@0.1.0;

interface attestation {
  attestation: func(report-data: list<u8>) -> result<list<u8>, string>;
}

interface run {
  run: func() -> list<u8>;
}

world hal-consumer {
  import attestation;
  export run;
}
