# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: propeller-prometheus
    url: http://propeller-prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Jaeger
    type: jaeger
    uid: propeller-jaeger
    url: http://magistrala-jaeger:16686
    access: proxy
    editable: true
