FROM golang:1.27-alpine3.24 AS builder

FROM gcr.io/distroless/cc-debian13

LABEL org.opencontainers.image.source=https://github.com/absmach/propeller
LABEL org.opencontainers.image.licenses=Apache-2.0

ARG SVC
COPY $SVC /exe
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/exe"]
