// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/absmach/propeller/pkg/proplet"
	"github.com/absmach/propeller/pkg/task"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// SelectProplet provides a mock function for the type MockScheduler
func (_mock *MockScheduler) SelectProplet(t task.Task, proplets []proplet.Proplet) (proplet.Proplet, error) {
	ret := _mock.Called(t, proplets)

	if len(ret) == 0 {
		panic("no return value specified for SelectProplet")
	}

	var r0 proplet.Proplet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(task.Task, []proplet.Proplet) (proplet.Proplet, error)); ok {
		return returnFunc(t, proplets)
	}
	if returnFunc, ok := ret.Get(0).(func(task.Task, []proplet.Proplet) proplet.Proplet); ok {
		r0 = returnFunc(t, proplets)
	} else {
		r0 = ret.Get(0).(proplet.Proplet)
	}
	if returnFunc, ok := ret.Get(1).(func(task.Task, []proplet.Proplet) error); ok {
		r1 = returnFunc(t, proplets)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduler_SelectProplet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectProplet'
type MockScheduler_SelectProplet_Call struct {
	*mock.Call
}

// SelectProplet is a helper method to define mock.On call
//   - t task.Task
//   - proplets []proplet.Proplet
func (_e *MockScheduler_Expecter) SelectProplet(t interface{}, proplets interface{}) *MockScheduler_SelectProplet_Call {
	return &MockScheduler_SelectProplet_Call{Call: _e.mock.On("SelectProplet", t, proplets)}
}

func (_c *MockScheduler_SelectProplet_Call) Run(run func(t task.Task, proplets []proplet.Proplet)) *MockScheduler_SelectProplet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 task.Task
		if args[0] != nil {
			arg0 = args[0].(task.Task)
		}
		var arg1 []proplet.Proplet
		if args[1] != nil {
			arg1 = args[1].([]proplet.Proplet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduler_SelectProplet_Call) Return(proplet1 proplet.Proplet, err error) *MockScheduler_SelectProplet_Call {
	_c.Call.Return(proplet1, err)
	return _c
}

func (_c *MockScheduler_SelectProplet_Call) RunAndReturn(run func(t task.Task, proplets []proplet.Proplet) (proplet.Proplet, error)) *MockScheduler_SelectProplet_Call {
	_c.Call.Return(run)
	return _c
}
