// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/propeller/manager"
	"github.com/absmach/propeller/pkg/proplet"
	"github.com/absmach/propeller/pkg/task"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ConfigureExperiment provides a mock function for the type MockService
func (_mock *MockService) ConfigureExperiment(ctx context.Context, config manager.ExperimentConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for ConfigureExperiment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manager.ExperimentConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ConfigureExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureExperiment'
type MockService_ConfigureExperiment_Call struct {
	*mock.Call
}

// ConfigureExperiment is a helper method to define mock.On call
//   - ctx context.Context
//   - config manager.ExperimentConfig
func (_e *MockService_Expecter) ConfigureExperiment(ctx interface{}, config interface{}) *MockService_ConfigureExperiment_Call {
	return &MockService_ConfigureExperiment_Call{Call: _e.mock.On("ConfigureExperiment", ctx, config)}
}

func (_c *MockService_ConfigureExperiment_Call) Run(run func(ctx context.Context, config manager.ExperimentConfig)) *MockService_ConfigureExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manager.ExperimentConfig
		if args[1] != nil {
			arg1 = args[1].(manager.ExperimentConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ConfigureExperiment_Call) Return(err error) *MockService_ConfigureExperiment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ConfigureExperiment_Call) RunAndReturn(run func(ctx context.Context, config manager.ExperimentConfig) error) *MockService_ConfigureExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJob provides a mock function for the type MockService
func (_mock *MockService) CreateJob(ctx context.Context, name string, tasks []task.Task, executionMode string) (string, []task.Task, error) {
	ret := _mock.Called(ctx, name, tasks, executionMode)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 string
	var r1 []task.Task
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []task.Task, string) (string, []task.Task, error)); ok {
		return returnFunc(ctx, name, tasks, executionMode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []task.Task, string) string); ok {
		r0 = returnFunc(ctx, name, tasks, executionMode)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []task.Task, string) []task.Task); ok {
		r1 = returnFunc(ctx, name, tasks, executionMode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]task.Task)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []task.Task, string) error); ok {
		r2 = returnFunc(ctx, name, tasks, executionMode)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockService_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - tasks []task.Task
//   - executionMode string
func (_e *MockService_Expecter) CreateJob(ctx interface{}, name interface{}, tasks interface{}, executionMode interface{}) *MockService_CreateJob_Call {
	return &MockService_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, name, tasks, executionMode)}
}

func (_c *MockService_CreateJob_Call) Run(run func(ctx context.Context, name string, tasks []task.Task, executionMode string)) *MockService_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []task.Task
		if args[2] != nil {
			arg2 = args[2].([]task.Task)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_CreateJob_Call) Return(s string, tasks1 []task.Task, err error) *MockService_CreateJob_Call {
	_c.Call.Return(s, tasks1, err)
	return _c
}

func (_c *MockService_CreateJob_Call) RunAndReturn(run func(ctx context.Context, name string, tasks []task.Task, executionMode string) (string, []task.Task, error)) *MockService_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function for the type MockService
func (_mock *MockService) CreateTask(ctx context.Context, task1 task.Task) (task.Task, error) {
	ret := _mock.Called(ctx, task1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) (task.Task, error)); ok {
		return returnFunc(ctx, task1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) task.Task); ok {
		r0 = returnFunc(ctx, task1)
	} else {
		r0 = ret.Get(0).(task.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task.Task) error); ok {
		r1 = returnFunc(ctx, task1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task1 task.Task
func (_e *MockService_Expecter) CreateTask(ctx interface{}, task1 interface{}) *MockService_CreateTask_Call {
	return &MockService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task1)}
}

func (_c *MockService_CreateTask_Call) Run(run func(ctx context.Context, task1 task.Task)) *MockService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.Task
		if args[1] != nil {
			arg1 = args[1].(task.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateTask_Call) Return(task11 task.Task, err error) *MockService_CreateTask_Call {
	_c.Call.Return(task11, err)
	return _c
}

func (_c *MockService_CreateTask_Call) RunAndReturn(run func(ctx context.Context, task1 task.Task) (task.Task, error)) *MockService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkflow provides a mock function for the type MockService
func (_mock *MockService) CreateWorkflow(ctx context.Context, tasks []task.Task) ([]task.Task, error) {
	ret := _mock.Called(ctx, tasks)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkflow")
	}

	var r0 []task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []task.Task) ([]task.Task, error)); ok {
		return returnFunc(ctx, tasks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []task.Task) []task.Task); ok {
		r0 = returnFunc(ctx, tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []task.Task) error); ok {
		r1 = returnFunc(ctx, tasks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkflow'
type MockService_CreateWorkflow_Call struct {
	*mock.Call
}

// CreateWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - tasks []task.Task
func (_e *MockService_Expecter) CreateWorkflow(ctx interface{}, tasks interface{}) *MockService_CreateWorkflow_Call {
	return &MockService_CreateWorkflow_Call{Call: _e.mock.On("CreateWorkflow", ctx, tasks)}
}

func (_c *MockService_CreateWorkflow_Call) Run(run func(ctx context.Context, tasks []task.Task)) *MockService_CreateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []task.Task
		if args[1] != nil {
			arg1 = args[1].([]task.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateWorkflow_Call) Return(tasks1 []task.Task, err error) *MockService_CreateWorkflow_Call {
	_c.Call.Return(tasks1, err)
	return _c
}

func (_c *MockService_CreateWorkflow_Call) RunAndReturn(run func(ctx context.Context, tasks []task.Task) ([]task.Task, error)) *MockService_CreateWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProplet provides a mock function for the type MockService
func (_mock *MockService) DeleteProplet(ctx context.Context, propletID string) error {
	ret := _mock.Called(ctx, propletID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProplet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, propletID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteProplet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProplet'
type MockService_DeleteProplet_Call struct {
	*mock.Call
}

// DeleteProplet is a helper method to define mock.On call
//   - ctx context.Context
//   - propletID string
func (_e *MockService_Expecter) DeleteProplet(ctx interface{}, propletID interface{}) *MockService_DeleteProplet_Call {
	return &MockService_DeleteProplet_Call{Call: _e.mock.On("DeleteProplet", ctx, propletID)}
}

func (_c *MockService_DeleteProplet_Call) Run(run func(ctx context.Context, propletID string)) *MockService_DeleteProplet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteProplet_Call) Return(err error) *MockService_DeleteProplet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteProplet_Call) RunAndReturn(run func(ctx context.Context, propletID string) error) *MockService_DeleteProplet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockService
func (_mock *MockService) DeleteTask(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockService_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockService_Expecter) DeleteTask(ctx interface{}, taskID interface{}) *MockService_DeleteTask_Call {
	return &MockService_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, taskID)}
}

func (_c *MockService_DeleteTask_Call) Run(run func(ctx context.Context, taskID string)) *MockService_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteTask_Call) Return(err error) *MockService_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteTask_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *MockService_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetFLTask provides a mock function for the type MockService
func (_mock *MockService) GetFLTask(ctx context.Context, roundID string, propletID string) (manager.FLTask, error) {
	ret := _mock.Called(ctx, roundID, propletID)

	if len(ret) == 0 {
		panic("no return value specified for GetFLTask")
	}

	var r0 manager.FLTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (manager.FLTask, error)); ok {
		return returnFunc(ctx, roundID, propletID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) manager.FLTask); ok {
		r0 = returnFunc(ctx, roundID, propletID)
	} else {
		r0 = ret.Get(0).(manager.FLTask)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, roundID, propletID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetFLTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFLTask'
type MockService_GetFLTask_Call struct {
	*mock.Call
}

// GetFLTask is a helper method to define mock.On call
//   - ctx context.Context
//   - roundID string
//   - propletID string
func (_e *MockService_Expecter) GetFLTask(ctx interface{}, roundID interface{}, propletID interface{}) *MockService_GetFLTask_Call {
	return &MockService_GetFLTask_Call{Call: _e.mock.On("GetFLTask", ctx, roundID, propletID)}
}

func (_c *MockService_GetFLTask_Call) Run(run func(ctx context.Context, roundID string, propletID string)) *MockService_GetFLTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetFLTask_Call) Return(fLTask manager.FLTask, err error) *MockService_GetFLTask_Call {
	_c.Call.Return(fLTask, err)
	return _c
}

func (_c *MockService_GetFLTask_Call) RunAndReturn(run func(ctx context.Context, roundID string, propletID string) (manager.FLTask, error)) *MockService_GetFLTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetJob provides a mock function for the type MockService
func (_mock *MockService) GetJob(ctx context.Context, jobID string) ([]task.Task, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 []task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]task.Task, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []task.Task); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockService_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockService_Expecter) GetJob(ctx interface{}, jobID interface{}) *MockService_GetJob_Call {
	return &MockService_GetJob_Call{Call: _e.mock.On("GetJob", ctx, jobID)}
}

func (_c *MockService_GetJob_Call) Run(run func(ctx context.Context, jobID string)) *MockService_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetJob_Call) Return(tasks []task.Task, err error) *MockService_GetJob_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockService_GetJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) ([]task.Task, error)) *MockService_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetParentResults provides a mock function for the type MockService
func (_mock *MockService) GetParentResults(ctx context.Context, taskID string) (map[string]any, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetParentResults")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]any, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]any); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetParentResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParentResults'
type MockService_GetParentResults_Call struct {
	*mock.Call
}

// GetParentResults is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockService_Expecter) GetParentResults(ctx interface{}, taskID interface{}) *MockService_GetParentResults_Call {
	return &MockService_GetParentResults_Call{Call: _e.mock.On("GetParentResults", ctx, taskID)}
}

func (_c *MockService_GetParentResults_Call) Run(run func(ctx context.Context, taskID string)) *MockService_GetParentResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetParentResults_Call) Return(stringToV map[string]any, err error) *MockService_GetParentResults_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockService_GetParentResults_Call) RunAndReturn(run func(ctx context.Context, taskID string) (map[string]any, error)) *MockService_GetParentResults_Call {
	_c.Call.Return(run)
	return _c
}

// GetProplet provides a mock function for the type MockService
func (_mock *MockService) GetProplet(ctx context.Context, propletID string) (proplet.Proplet, error) {
	ret := _mock.Called(ctx, propletID)

	if len(ret) == 0 {
		panic("no return value specified for GetProplet")
	}

	var r0 proplet.Proplet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (proplet.Proplet, error)); ok {
		return returnFunc(ctx, propletID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) proplet.Proplet); ok {
		r0 = returnFunc(ctx, propletID)
	} else {
		r0 = ret.Get(0).(proplet.Proplet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, propletID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetProplet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProplet'
type MockService_GetProplet_Call struct {
	*mock.Call
}

// GetProplet is a helper method to define mock.On call
//   - ctx context.Context
//   - propletID string
func (_e *MockService_Expecter) GetProplet(ctx interface{}, propletID interface{}) *MockService_GetProplet_Call {
	return &MockService_GetProplet_Call{Call: _e.mock.On("GetProplet", ctx, propletID)}
}

func (_c *MockService_GetProplet_Call) Run(run func(ctx context.Context, propletID string)) *MockService_GetProplet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetProplet_Call) Return(proplet1 proplet.Proplet, err error) *MockService_GetProplet_Call {
	_c.Call.Return(proplet1, err)
	return _c
}

func (_c *MockService_GetProplet_Call) RunAndReturn(run func(ctx context.Context, propletID string) (proplet.Proplet, error)) *MockService_GetProplet_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropletMetrics provides a mock function for the type MockService
func (_mock *MockService) GetPropletMetrics(ctx context.Context, propletID string, offset uint64, limit uint64) (manager.PropletMetricsPage, error) {
	ret := _mock.Called(ctx, propletID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPropletMetrics")
	}

	var r0 manager.PropletMetricsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) (manager.PropletMetricsPage, error)); ok {
		return returnFunc(ctx, propletID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) manager.PropletMetricsPage); ok {
		r0 = returnFunc(ctx, propletID, offset, limit)
	} else {
		r0 = ret.Get(0).(manager.PropletMetricsPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, propletID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetPropletMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropletMetrics'
type MockService_GetPropletMetrics_Call struct {
	*mock.Call
}

// GetPropletMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - propletID string
//   - offset uint64
//   - limit uint64
func (_e *MockService_Expecter) GetPropletMetrics(ctx interface{}, propletID interface{}, offset interface{}, limit interface{}) *MockService_GetPropletMetrics_Call {
	return &MockService_GetPropletMetrics_Call{Call: _e.mock.On("GetPropletMetrics", ctx, propletID, offset, limit)}
}

func (_c *MockService_GetPropletMetrics_Call) Run(run func(ctx context.Context, propletID string, offset uint64, limit uint64)) *MockService_GetPropletMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetPropletMetrics_Call) Return(propletMetricsPage manager.PropletMetricsPage, err error) *MockService_GetPropletMetrics_Call {
	_c.Call.Return(propletMetricsPage, err)
	return _c
}

func (_c *MockService_GetPropletMetrics_Call) RunAndReturn(run func(ctx context.Context, propletID string, offset uint64, limit uint64) (manager.PropletMetricsPage, error)) *MockService_GetPropletMetrics_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockService) GetPropletAliveHistory(ctx context.Context, propletID string, offset uint64, limit uint64) (proplet.PropletAliveHistoryPage, error) {
	ret := _mock.Called(ctx, propletID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPropletAliveHistory")
	}

	var r0 proplet.PropletAliveHistoryPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) (proplet.PropletAliveHistoryPage, error)); ok {
		return returnFunc(ctx, propletID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) proplet.PropletAliveHistoryPage); ok {
		r0 = returnFunc(ctx, propletID, offset, limit)
	} else {
		r0 = ret.Get(0).(proplet.PropletAliveHistoryPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, propletID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockService_GetPropletAliveHistory_Call struct {
	*mock.Call
}

func (_e *MockService_Expecter) GetPropletAliveHistory(ctx any, propletID any, offset any, limit any) *MockService_GetPropletAliveHistory_Call {
	return &MockService_GetPropletAliveHistory_Call{Call: _e.mock.On("GetPropletAliveHistory", ctx, propletID, offset, limit)}
}

func (_c *MockService_GetPropletAliveHistory_Call) Run(run func(ctx context.Context, propletID string, offset uint64, limit uint64)) *MockService_GetPropletAliveHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockService_GetPropletAliveHistory_Call) Return(page proplet.PropletAliveHistoryPage, err error) *MockService_GetPropletAliveHistory_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockService_GetPropletAliveHistory_Call) RunAndReturn(run func(ctx context.Context, propletID string, offset uint64, limit uint64) (proplet.PropletAliveHistoryPage, error)) *MockService_GetPropletAliveHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoundStatus provides a mock function for the type MockService
func (_mock *MockService) GetRoundStatus(ctx context.Context, roundID string) (manager.RoundStatus, error) {
	ret := _mock.Called(ctx, roundID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoundStatus")
	}

	var r0 manager.RoundStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (manager.RoundStatus, error)); ok {
		return returnFunc(ctx, roundID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) manager.RoundStatus); ok {
		r0 = returnFunc(ctx, roundID)
	} else {
		r0 = ret.Get(0).(manager.RoundStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roundID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetRoundStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoundStatus'
type MockService_GetRoundStatus_Call struct {
	*mock.Call
}

// GetRoundStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - roundID string
func (_e *MockService_Expecter) GetRoundStatus(ctx interface{}, roundID interface{}) *MockService_GetRoundStatus_Call {
	return &MockService_GetRoundStatus_Call{Call: _e.mock.On("GetRoundStatus", ctx, roundID)}
}

func (_c *MockService_GetRoundStatus_Call) Run(run func(ctx context.Context, roundID string)) *MockService_GetRoundStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetRoundStatus_Call) Return(roundStatus manager.RoundStatus, err error) *MockService_GetRoundStatus_Call {
	_c.Call.Return(roundStatus, err)
	return _c
}

func (_c *MockService_GetRoundStatus_Call) RunAndReturn(run func(ctx context.Context, roundID string) (manager.RoundStatus, error)) *MockService_GetRoundStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockService
func (_mock *MockService) GetTask(ctx context.Context, taskID string) (task.Task, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (task.Task, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) task.Task); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Get(0).(task.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockService_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockService_Expecter) GetTask(ctx interface{}, taskID interface{}) *MockService_GetTask_Call {
	return &MockService_GetTask_Call{Call: _e.mock.On("GetTask", ctx, taskID)}
}

func (_c *MockService_GetTask_Call) Run(run func(ctx context.Context, taskID string)) *MockService_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetTask_Call) Return(task1 task.Task, err error) *MockService_GetTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockService_GetTask_Call) RunAndReturn(run func(ctx context.Context, taskID string) (task.Task, error)) *MockService_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskMetrics provides a mock function for the type MockService
func (_mock *MockService) GetTaskMetrics(ctx context.Context, taskID string, offset uint64, limit uint64) (manager.TaskMetricsPage, error) {
	ret := _mock.Called(ctx, taskID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskMetrics")
	}

	var r0 manager.TaskMetricsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) (manager.TaskMetricsPage, error)); ok {
		return returnFunc(ctx, taskID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) manager.TaskMetricsPage); ok {
		r0 = returnFunc(ctx, taskID, offset, limit)
	} else {
		r0 = ret.Get(0).(manager.TaskMetricsPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, taskID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetTaskMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskMetrics'
type MockService_GetTaskMetrics_Call struct {
	*mock.Call
}

// GetTaskMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - offset uint64
//   - limit uint64
func (_e *MockService_Expecter) GetTaskMetrics(ctx interface{}, taskID interface{}, offset interface{}, limit interface{}) *MockService_GetTaskMetrics_Call {
	return &MockService_GetTaskMetrics_Call{Call: _e.mock.On("GetTaskMetrics", ctx, taskID, offset, limit)}
}

func (_c *MockService_GetTaskMetrics_Call) Run(run func(ctx context.Context, taskID string, offset uint64, limit uint64)) *MockService_GetTaskMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetTaskMetrics_Call) Return(taskMetricsPage manager.TaskMetricsPage, err error) *MockService_GetTaskMetrics_Call {
	_c.Call.Return(taskMetricsPage, err)
	return _c
}

func (_c *MockService_GetTaskMetrics_Call) RunAndReturn(run func(ctx context.Context, taskID string, offset uint64, limit uint64) (manager.TaskMetricsPage, error)) *MockService_GetTaskMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskResults provides a mock function for the type MockService
func (_mock *MockService) GetTaskResults(ctx context.Context, taskID string) (any, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskResults")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (any, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetTaskResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskResults'
type MockService_GetTaskResults_Call struct {
	*mock.Call
}

// GetTaskResults is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockService_Expecter) GetTaskResults(ctx interface{}, taskID interface{}) *MockService_GetTaskResults_Call {
	return &MockService_GetTaskResults_Call{Call: _e.mock.On("GetTaskResults", ctx, taskID)}
}

func (_c *MockService_GetTaskResults_Call) Run(run func(ctx context.Context, taskID string)) *MockService_GetTaskResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetTaskResults_Call) Return(v any, err error) *MockService_GetTaskResults_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_GetTaskResults_Call) RunAndReturn(run func(ctx context.Context, taskID string) (any, error)) *MockService_GetTaskResults_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobs provides a mock function for the type MockService
func (_mock *MockService) ListJobs(ctx context.Context, offset uint64, limit uint64) (manager.JobPage, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListJobs")
	}

	var r0 manager.JobPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (manager.JobPage, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) manager.JobPage); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		r0 = ret.Get(0).(manager.JobPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobs'
type MockService_ListJobs_Call struct {
	*mock.Call
}

// ListJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *MockService_Expecter) ListJobs(ctx interface{}, offset interface{}, limit interface{}) *MockService_ListJobs_Call {
	return &MockService_ListJobs_Call{Call: _e.mock.On("ListJobs", ctx, offset, limit)}
}

func (_c *MockService_ListJobs_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *MockService_ListJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListJobs_Call) Return(jobPage manager.JobPage, err error) *MockService_ListJobs_Call {
	_c.Call.Return(jobPage, err)
	return _c
}

func (_c *MockService_ListJobs_Call) RunAndReturn(run func(ctx context.Context, offset uint64, limit uint64) (manager.JobPage, error)) *MockService_ListJobs_Call {
	_c.Call.Return(run)
	return _c
}

// ListProplets provides a mock function for the type MockService
func (_mock *MockService) ListProplets(ctx context.Context, offset uint64, limit uint64) (proplet.PropletPage, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListProplets")
	}

	var r0 proplet.PropletPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (proplet.PropletPage, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) proplet.PropletPage); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		r0 = ret.Get(0).(proplet.PropletPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListProplets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProplets'
type MockService_ListProplets_Call struct {
	*mock.Call
}

// ListProplets is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *MockService_Expecter) ListProplets(ctx interface{}, offset interface{}, limit interface{}) *MockService_ListProplets_Call {
	return &MockService_ListProplets_Call{Call: _e.mock.On("ListProplets", ctx, offset, limit)}
}

func (_c *MockService_ListProplets_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *MockService_ListProplets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListProplets_Call) Return(propletPage proplet.PropletPage, err error) *MockService_ListProplets_Call {
	_c.Call.Return(propletPage, err)
	return _c
}

func (_c *MockService_ListProplets_Call) RunAndReturn(run func(ctx context.Context, offset uint64, limit uint64) (proplet.PropletPage, error)) *MockService_ListProplets_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockService
func (_mock *MockService) ListTasks(ctx context.Context, offset uint64, limit uint64) (task.TaskPage, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 task.TaskPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) (task.TaskPage, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) task.TaskPage); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		r0 = ret.Get(0).(task.TaskPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockService_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *MockService_Expecter) ListTasks(ctx interface{}, offset interface{}, limit interface{}) *MockService_ListTasks_Call {
	return &MockService_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, offset, limit)}
}

func (_c *MockService_ListTasks_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *MockService_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListTasks_Call) Return(taskPage task.TaskPage, err error) *MockService_ListTasks_Call {
	_c.Call.Return(taskPage, err)
	return _c
}

func (_c *MockService_ListTasks_Call) RunAndReturn(run func(ctx context.Context, offset uint64, limit uint64) (task.TaskPage, error)) *MockService_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// PostFLUpdate provides a mock function for the type MockService
func (_mock *MockService) PostFLUpdate(ctx context.Context, update manager.FLUpdate) error {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for PostFLUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manager.FLUpdate) error); ok {
		r0 = returnFunc(ctx, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_PostFLUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostFLUpdate'
type MockService_PostFLUpdate_Call struct {
	*mock.Call
}

// PostFLUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - update manager.FLUpdate
func (_e *MockService_Expecter) PostFLUpdate(ctx interface{}, update interface{}) *MockService_PostFLUpdate_Call {
	return &MockService_PostFLUpdate_Call{Call: _e.mock.On("PostFLUpdate", ctx, update)}
}

func (_c *MockService_PostFLUpdate_Call) Run(run func(ctx context.Context, update manager.FLUpdate)) *MockService_PostFLUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manager.FLUpdate
		if args[1] != nil {
			arg1 = args[1].(manager.FLUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_PostFLUpdate_Call) Return(err error) *MockService_PostFLUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_PostFLUpdate_Call) RunAndReturn(run func(ctx context.Context, update manager.FLUpdate) error) *MockService_PostFLUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// PostFLUpdateCBOR provides a mock function for the type MockService
func (_mock *MockService) PostFLUpdateCBOR(ctx context.Context, updateData []byte) error {
	ret := _mock.Called(ctx, updateData)

	if len(ret) == 0 {
		panic("no return value specified for PostFLUpdateCBOR")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, updateData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_PostFLUpdateCBOR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostFLUpdateCBOR'
type MockService_PostFLUpdateCBOR_Call struct {
	*mock.Call
}

// PostFLUpdateCBOR is a helper method to define mock.On call
//   - ctx context.Context
//   - updateData []byte
func (_e *MockService_Expecter) PostFLUpdateCBOR(ctx interface{}, updateData interface{}) *MockService_PostFLUpdateCBOR_Call {
	return &MockService_PostFLUpdateCBOR_Call{Call: _e.mock.On("PostFLUpdateCBOR", ctx, updateData)}
}

func (_c *MockService_PostFLUpdateCBOR_Call) Run(run func(ctx context.Context, updateData []byte)) *MockService_PostFLUpdateCBOR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_PostFLUpdateCBOR_Call) Return(err error) *MockService_PostFLUpdateCBOR_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_PostFLUpdateCBOR_Call) RunAndReturn(run func(ctx context.Context, updateData []byte) error) *MockService_PostFLUpdateCBOR_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverInterruptedTasks provides a mock function for the type MockService
func (_mock *MockService) RecoverInterruptedTasks(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RecoverInterruptedTasks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RecoverInterruptedTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverInterruptedTasks'
type MockService_RecoverInterruptedTasks_Call struct {
	*mock.Call
}

// RecoverInterruptedTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) RecoverInterruptedTasks(ctx interface{}) *MockService_RecoverInterruptedTasks_Call {
	return &MockService_RecoverInterruptedTasks_Call{Call: _e.mock.On("RecoverInterruptedTasks", ctx)}
}

func (_c *MockService_RecoverInterruptedTasks_Call) Run(run func(ctx context.Context)) *MockService_RecoverInterruptedTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_RecoverInterruptedTasks_Call) Return(err error) *MockService_RecoverInterruptedTasks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RecoverInterruptedTasks_Call) RunAndReturn(run func(ctx context.Context) error) *MockService_RecoverInterruptedTasks_Call {
	_c.Call.Return(run)
	return _c
}

// SelectProplet provides a mock function for the type MockService
func (_mock *MockService) SelectProplet(ctx context.Context, task1 task.Task) (proplet.Proplet, error) {
	ret := _mock.Called(ctx, task1)

	if len(ret) == 0 {
		panic("no return value specified for SelectProplet")
	}

	var r0 proplet.Proplet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) (proplet.Proplet, error)); ok {
		return returnFunc(ctx, task1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) proplet.Proplet); ok {
		r0 = returnFunc(ctx, task1)
	} else {
		r0 = ret.Get(0).(proplet.Proplet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task.Task) error); ok {
		r1 = returnFunc(ctx, task1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SelectProplet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectProplet'
type MockService_SelectProplet_Call struct {
	*mock.Call
}

// SelectProplet is a helper method to define mock.On call
//   - ctx context.Context
//   - task1 task.Task
func (_e *MockService_Expecter) SelectProplet(ctx interface{}, task1 interface{}) *MockService_SelectProplet_Call {
	return &MockService_SelectProplet_Call{Call: _e.mock.On("SelectProplet", ctx, task1)}
}

func (_c *MockService_SelectProplet_Call) Run(run func(ctx context.Context, task1 task.Task)) *MockService_SelectProplet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.Task
		if args[1] != nil {
			arg1 = args[1].(task.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SelectProplet_Call) Return(proplet1 proplet.Proplet, err error) *MockService_SelectProplet_Call {
	_c.Call.Return(proplet1, err)
	return _c
}

func (_c *MockService_SelectProplet_Call) RunAndReturn(run func(ctx context.Context, task1 task.Task) (proplet.Proplet, error)) *MockService_SelectProplet_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockService
func (_mock *MockService) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Shutdown(ctx interface{}) *MockService_Shutdown_Call {
	return &MockService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockService_Shutdown_Call) Run(run func(ctx context.Context)) *MockService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Shutdown_Call) Return(err error) *MockService_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// StartJob provides a mock function for the type MockService
func (_mock *MockService) StartJob(ctx context.Context, jobID string) error {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for StartJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_StartJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJob'
type MockService_StartJob_Call struct {
	*mock.Call
}

// StartJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockService_Expecter) StartJob(ctx interface{}, jobID interface{}) *MockService_StartJob_Call {
	return &MockService_StartJob_Call{Call: _e.mock.On("StartJob", ctx, jobID)}
}

func (_c *MockService_StartJob_Call) Run(run func(ctx context.Context, jobID string)) *MockService_StartJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StartJob_Call) Return(err error) *MockService_StartJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_StartJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) error) *MockService_StartJob_Call {
	_c.Call.Return(run)
	return _c
}

// StartTask provides a mock function for the type MockService
func (_mock *MockService) StartTask(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for StartTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_StartTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTask'
type MockService_StartTask_Call struct {
	*mock.Call
}

// StartTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockService_Expecter) StartTask(ctx interface{}, taskID interface{}) *MockService_StartTask_Call {
	return &MockService_StartTask_Call{Call: _e.mock.On("StartTask", ctx, taskID)}
}

func (_c *MockService_StartTask_Call) Run(run func(ctx context.Context, taskID string)) *MockService_StartTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StartTask_Call) Return(err error) *MockService_StartTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_StartTask_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *MockService_StartTask_Call {
	_c.Call.Return(run)
	return _c
}

// StopJob provides a mock function for the type MockService
func (_mock *MockService) StopJob(ctx context.Context, jobID string) error {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for StopJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_StopJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopJob'
type MockService_StopJob_Call struct {
	*mock.Call
}

// StopJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockService_Expecter) StopJob(ctx interface{}, jobID interface{}) *MockService_StopJob_Call {
	return &MockService_StopJob_Call{Call: _e.mock.On("StopJob", ctx, jobID)}
}

func (_c *MockService_StopJob_Call) Run(run func(ctx context.Context, jobID string)) *MockService_StopJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StopJob_Call) Return(err error) *MockService_StopJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_StopJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) error) *MockService_StopJob_Call {
	_c.Call.Return(run)
	return _c
}

// StopTask provides a mock function for the type MockService
func (_mock *MockService) StopTask(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for StopTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_StopTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopTask'
type MockService_StopTask_Call struct {
	*mock.Call
}

// StopTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockService_Expecter) StopTask(ctx interface{}, taskID interface{}) *MockService_StopTask_Call {
	return &MockService_StopTask_Call{Call: _e.mock.On("StopTask", ctx, taskID)}
}

func (_c *MockService_StopTask_Call) Run(run func(ctx context.Context, taskID string)) *MockService_StopTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StopTask_Call) Return(err error) *MockService_StopTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_StopTask_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *MockService_StopTask_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockService
func (_mock *MockService) Subscribe(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockService_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Subscribe(ctx interface{}) *MockService_Subscribe_Call {
	return &MockService_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx)}
}

func (_c *MockService_Subscribe_Call) Run(run func(ctx context.Context)) *MockService_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Subscribe_Call) Return(err error) *MockService_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Subscribe_Call) RunAndReturn(run func(ctx context.Context) error) *MockService_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type MockService
func (_mock *MockService) UpdateTask(ctx context.Context, task1 task.Task) (task.Task, error) {
	ret := _mock.Called(ctx, task1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) (task.Task, error)); ok {
		return returnFunc(ctx, task1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.Task) task.Task); ok {
		r0 = returnFunc(ctx, task1)
	} else {
		r0 = ret.Get(0).(task.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task.Task) error); ok {
		r1 = returnFunc(ctx, task1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task1 task.Task
func (_e *MockService_Expecter) UpdateTask(ctx interface{}, task1 interface{}) *MockService_UpdateTask_Call {
	return &MockService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, task1)}
}

func (_c *MockService_UpdateTask_Call) Run(run func(ctx context.Context, task1 task.Task)) *MockService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.Task
		if args[1] != nil {
			arg1 = args[1].(task.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_UpdateTask_Call) Return(task11 task.Task, err error) *MockService_UpdateTask_Call {
	_c.Call.Return(task11, err)
	return _c
}

func (_c *MockService_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, task1 task.Task) (task.Task, error)) *MockService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
