package main

// Model coefficients extracted from trained LinearRegression model
// These values represent: y = intercept + coef[0]*x[0] + coef[1]*x[1]
// Generated by train_model.py from sklearn LinearRegression
const (
	// intercept is the model's bias term (y-intercept)
	modelIntercept = 0.0000000000000008881784197001252
	// modelCoefficients are the learned weights for each input feature
	modelCoefficient0 = 1.9999999999999996 // weight for input[0]
	modelCoefficient1 = 2.999999999999999  // weight for input[1]
)

// score computes the model prediction: y = intercept + coef0*x0 + coef1*x1
// This is a linear regression model trained to approximate: y = 2*x0 + 3*x1
func score(input []float64) float64 {
	if len(input) < 2 {
		return modelIntercept
	}
	return modelIntercept + input[0]*modelCoefficient0 + input[1]*modelCoefficient1
}
