name: Go Continuous Integration Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  go-lint-and-build:
    name: Go Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          cache-dependency-path: "go.sum"

      - name: Run linters
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7.2
          args: --config ./.golangci.yaml

      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.40.1/tinygo_0.40.1_amd64.deb
          sudo dpkg -i tinygo_0.40.1_amd64.deb

      - name: Install wasmtools
        run: cargo install --locked wasm-tools

      - name: Add wasm32-wasip2 target
        run: rustup target add wasm32-wasip2

      - name: Build Artifacts
        run: make all -j $(nproc)
